updated scripts after failing run

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,6 +1,15 @@
 #!/usr/bin/env bash
 set -e
 
+if ! [ -f ".env" ]; then
+  echo ".env file not found. exiting"
+  exit 1
+fi
+
+if ! [ $(command -v now) ]; then
+  npm i -g now
+fi
+
 function deploy_api
 {
   if ! [ -f "packages/api-server" ]; then
